import Header from "@/components/sections/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const aeonikProBold = localFont({
  src: "./fonts/AeonikPro-Bold.woff",
  variable: "--font-aeonik-pro-bold",
  weight: "700",
});

const aeonikProMedium = localFont({
  src: "./fonts/AeonikPro-Medium.woff",
  variable: "--font-aeonik-pro-medium",
  weight: "500",
});

const aeonikPro = localFont({
  src: "./fonts/AeonikPro-Regular.woff",
  variable: "--font-aeonik-pro",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${aeonikProBold.variable} ${aeonikProMedium.variable} ${aeonikPro.variable} relative antialiased dark`}
      >
        <div className="fixed -z-0 top-0 left-0 w-full h-screen object-center">
          <Image className="max-w-full" src="/assets/images/body-bg.png" width={1920} height={1080} alt="Dot square with opacity and dark screen" />
        </div>
        <Header />
        <main className="relative font-[family-name:var(--font-aeonik-pro)]">
          {children}
        </main>
      </body>
    </html>
  );
}
